language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

branches:
  except:
    - appveyor

install:
  - "pip install -IU setuptools"
  # Update pip for Python <= 3.4, so it supports install without -e tag
  - "pip install -IU pip"
  - "pip install ."
  - "pip install '.[tests]'"
  - "pip install '.[checkstyle]'"
  - "pip install -U '.[docs]'"
  - "pip install codecov"
# command to run tests
script:
  - 'flake8'
  - 'python -m pytest --cov=sirup --cov-report html --cov-config=.coveragerc  || [ $? -eq 5 ] && echo "No tests"'
  - 'cd docs; make html'

after_success:
  - codecov
