language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

branches:
  except:
    - appveyor

install:
  - "pip install -IU setuptools"
  - "pip install -e ."
  - "pip install -e '.[tests]'"
  - "pip install -e '.[docs]'"
  - "pip install -e '.[checkstyle]'"
  - "pip install codecov"
# command to run tests
script:
  - 'flake8'
  - 'python setup.py test || [ $? -eq 5 ] && echo "No tests"'
  - 'invoke coverage --no-html'
  - 'cd docs; make html'

after_success:
  - codecov --token=${CODECOV_UPLOADTOKEN}
