language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - "pip install -IU setuptools"
  - "pip install -r dev-requirements.txt"
# command to run tests
script: 'python setup.py test || [ $? -eq 5 ] && echo "No tests"'
