environment:

  matrix:
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

init:
  - "echo Testing with %PYTHON%"

install:
  # symlink python from a directory with a space
  - "mklink /d \"C:\\Program Files\\Python\" %PYTHON%"
  - "SET PYTHON=\"C:\\Program Files\\Python\""
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -I setuptools"
  - "python -m pip install -e %APPVEYOR_BUILD_FOLDER%"
  - "python -m pip install -e %APPVEYOR_BUILD_FOLDER%[tests]"
  - "python -m pip install -e %APPVEYOR_BUILD_FOLDER%[docs]"
  - "python -m pip install -e %APPVEYOR_BUILD_FOLDER%[checkstyle]"

build: off

test_script:
  - "flake8"
  - "if exist tests/*.py python setup.py test"
  - "docs/make.bat"
